## Atribuição

In [2]:
import numpy as np

In [14]:
a = np.array([[1,2,3,4,5], 
            [6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
np.sum(a, axis=0)

array([ 7,  9, 11, 13, 15])

In [18]:
a = np.random.randint(1,10,(2,3,4))
a

array([[[7, 2, 4, 2],
        [9, 2, 5, 5],
        [5, 3, 7, 4]],

       [[7, 8, 9, 6],
        [7, 6, 4, 2],
        [2, 1, 7, 8]]])

In [22]:
np.sum(a, axis=0) #soma cada item das matrizes com seu correspondente em profundidade

array([[14, 10, 13,  8],
       [16,  8,  9,  7],
       [ 7,  4, 14, 12]])

In [24]:
np.sum(a, axis=1) #soma cada coluna das matrizes e depois faz um "merge"

array([[21,  7, 16, 11],
       [16, 15, 20, 16]])

In [25]:
np.sum(a, axis=2) #soma cada linha das matrizes e depois faz um "merge"

array([[15, 21, 19],
       [30, 19, 18]])

### Comandos

In [26]:
np.min(a)

1

In [27]:
np.max(a)

9

In [29]:
np.max(a, axis=0) #compara cada item das matrizes com seu correspondente em profundidade

array([[7, 8, 9, 6],
       [9, 6, 5, 5],
       [5, 3, 7, 8]])

In [30]:
np.max(a, axis=1)

array([[9, 3, 7, 5],
       [7, 8, 9, 8]])

In [31]:
np.mean(a)

5.083333333333333

In [32]:
a

array([[[7, 2, 4, 2],
        [9, 2, 5, 5],
        [5, 3, 7, 4]],

       [[7, 8, 9, 6],
        [7, 6, 4, 2],
        [2, 1, 7, 8]]])

In [33]:
np.mean(a, axis=0)

array([[7. , 5. , 6.5, 4. ],
       [8. , 4. , 4.5, 3.5],
       [3.5, 2. , 7. , 6. ]])

In [34]:
c = np.array([1,2,3,4])
d = np.array([2,4,6,8])

In [35]:
np.any(c == 2)

True

In [36]:
np.any(d > 5)

True

In [37]:
np.any(c > 5)

False

In [38]:
d > 5

array([False, False,  True,  True])

In [39]:
np.any([False, False,  True,  True])

True

In [40]:
np.all(d > 2)

False

In [41]:
(d & 2 == 0) & (d > 2)

array([False,  True, False,  True])

## Broadcast

YaY \ 0 /
      |
     / \

In [45]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([10,20,30])

In [47]:
b+a

array([[11, 22, 33],
       [14, 25, 36]])

In [50]:
c = np.array([[10], 
              [20]])
c

array([[10],
       [20]])

In [49]:
a + c

array([[11, 12, 13],
       [24, 25, 26]])

- O formato do array com menos dimensões  é acrescido de 1 do lado esquerdo.
- Se os tamanhos não forem iguais em dimensão, o array tamanho igual a 1 numa determinada dimensão é esticado, repetindo seus elementos para ficar igual ao outro tamanho.
- Se os tamanhos dos arrays não forem iguais e nenhum dos dois for igual a 1, será retornado um erro.

In [51]:
print(a.shape)
print(b.shape)

(2, 3)
(3,)


In [54]:
a = np.array([1,2,3])
b = np.array([10,
              20,
              30])

In [55]:
c.shape

(2, 1)

### Quebrando o broadcast

In [59]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])
b = np.array([[1, 2], [3,4]])

In [60]:
a + b

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 

In [61]:
a = np.array([1,2,3,4])

In [62]:
a.reshape((2,2))

array([[1, 2],
       [3, 4]])

### Ordenação

In [63]:
a = np.array([4,1,3,5,2]) 
np.sort(a) # Organiza sem modificar os valores

array([1, 2, 3, 4, 5])

In [64]:
a

array([4, 1, 3, 5, 2])

In [65]:
a.sort() # Organiza e modifica os valores da array

In [66]:
a

array([1, 2, 3, 4, 5])

In [69]:
b = np.random.randint(1,10,(2,3,4))
b

array([[[1, 3, 3, 9],
        [3, 6, 3, 5],
        [5, 8, 2, 6]],

       [[7, 1, 4, 5],
        [4, 5, 4, 9],
        [9, 3, 7, 6]]])

In [70]:
np.sort(b, axis=0)

array([[[1, 1, 3, 5],
        [3, 5, 3, 5],
        [5, 3, 2, 6]],

       [[7, 3, 4, 9],
        [4, 6, 4, 9],
        [9, 8, 7, 6]]])

In [71]:
np.sort(b, axis=0)

array([[[1, 1, 3, 5],
        [3, 5, 3, 5],
        [5, 3, 2, 6]],

       [[7, 3, 4, 9],
        [4, 6, 4, 9],
        [9, 8, 7, 6]]])

In [72]:
np.sort(b, axis=None)

array([1, 1, 2, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 8, 9,
       9, 9])

In [74]:
a = np.array([4,1,3,5,2])
a

array([4, 1, 3, 5, 2])

In [75]:
np.argsort(a) #Ordena e mostra apenas os índices da matriz original ordenada

array([1, 4, 2, 0, 3], dtype=int64)

In [76]:
ind = np.argsort(a) #Serve como máscara de formatação

In [77]:
a[ind]

array([1, 2, 3, 4, 5])

In [81]:
x = np.array([40,10,30,50,20])
y = np.array([0,1,0,0,1])

In [85]:
ind = np.argsort(x)

In [86]:
x[ind]

array([10, 20, 30, 40, 50])

In [87]:
y[ind]

array([1, 1, 0, 0, 0])