In [1]:
import numpy as np

a array do numpy é mais rápida do que a lista do python

In [20]:
a = np.array([1,2,3,4,5])

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
type(a)

numpy.ndarray

In [23]:
a[0]

1

In [24]:
a[-1]

5

In [25]:
a.shape

(5,)

In [30]:
b = np.array([[1,2,3], [4,5,6]])

In [31]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b.shape

(2, 3)

In [35]:
b[0,1]

2

In [36]:
b[0]

array([1, 2, 3])

In [37]:
b[0][1]

2

In [38]:
b[0,1] = 20

In [39]:
b

array([[ 1, 20,  3],
       [ 4,  5,  6]])

In [40]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.array([0 for i in range(10)])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
np.zeros(5) #Padrão do np.zeros é float64

array([0., 0., 0., 0., 0.])

In [47]:
np.zeros((5,3), dtype = int) #Podemos passar como parâmetro um conversor

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [50]:
c = np.zeros(5)
c

array([0., 0., 0., 0., 0.])

In [51]:
c.dtype

dtype('float64')

In [58]:
np.full(5, "pedro")

array(['pedro', 'pedro', 'pedro', 'pedro', 'pedro'], dtype='<U5')

In [59]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.full(3,np.arange(3)) #cria um array 'cheia' de um certo elemento

array([0, 1, 2])

In [65]:
np.eye(5) #matriz identidade

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
np.full(5, np.random.random(5))

array([0.26503128, 0.96102673, 0.73074757, 0.81002154, 0.5449452 ])

In [75]:
np.random.randint(1,10,(5,3)) #inicio / fim / tamanho / dtype

array([[2, 1, 1],
       [7, 2, 3],
       [9, 8, 2],
       [7, 6, 9],
       [2, 9, 8]])

# Indexação

In [77]:
a = np.random.randint(1,10,5)
a

array([1, 9, 7, 2, 4])

In [78]:
a[2:4]

array([7, 2])

In [79]:
a[2:]

array([7, 2, 4])

In [80]:
a[:4]

array([1, 9, 7, 2])

In [82]:
a = np.random.randint(1,10,(3,5))
a

array([[2, 2, 1, 7, 4],
       [1, 5, 8, 6, 4],
       [3, 4, 8, 8, 3]])

In [83]:
a[0:2, 1:3]

array([[2, 1],
       [5, 8]])

In [89]:
b = a

In [90]:
a[0,1]

99

In [91]:
a[0,1] = 99
a

array([[ 2, 99,  1,  7,  4],
       [ 1,  5,  8,  6,  4],
       [ 3,  4,  8,  8,  3]])

In [92]:
b

array([[ 2, 99,  1,  7,  4],
       [ 1,  5,  8,  6,  4],
       [ 3,  4,  8,  8,  3]])

In [93]:
np.random.randint(0,1000,(300,300))

array([[346, 653, 514, ..., 495, 168, 955],
       [251, 383, 641, ..., 213, 670, 484],
       [337, 263, 266, ..., 609, 285,  78],
       ...,
       [982, 422, 894, ..., 136, 228, 928],
       [946, 570, 696, ..., 477, 732, 673],
       [853, 130, 528, ..., 308, 896,   0]])

In [95]:
c

array([0., 0., 0., 0., 0.])

In [98]:
c[0] = 11

In [100]:
c = b.copy()

## Slice com atribuição

In [104]:
a[0:2, 1:3] = 99
a

array([[ 2, 99, 99,  7,  4],
       [ 1, 99, 99,  6,  4],
       [ 3,  4,  8,  8,  3]])

In [111]:
b = np.random.randint(10, 20,(2,2))
b

array([[13, 15],
       [19, 17]])

In [112]:
a[0:2, 1:3] = b
a

array([[ 2, 13, 15,  7,  4],
       [ 1, 19, 17,  6,  4],
       [ 3,  4,  8,  8,  3]])

In [113]:
b = np.random.randint(10, 20,(3,3))
b

array([[10, 18, 13],
       [13, 11, 18],
       [10, 13, 18]])

In [114]:
a[0:2, 1:3] = b

ValueError: could not broadcast input array from shape (3,3) into shape (2,2)

## Indexação avançada

In [115]:
a = np.arange(1,11)

In [118]:
a[[True, True, True, True, True, False, False, False, False, False]] #Máscara


array([1, 2, 3, 4, 5])

In [120]:
mask = [True, False, True, False, True, False, True, False, True, False]
a[mask]

array([1, 3, 5, 7, 9])

In [122]:
a > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [124]:
mask = a > 5 # A máscara também pode ser criada com operadores lógicos
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [125]:
a[mask]

array([ 6,  7,  8,  9, 10])

In [127]:
a[a>5]

array([ 6,  7,  8,  9, 10])

In [126]:
mask = a % 3 == 0
a[mask]

array([3, 6, 9])

### E se tivéssemos mais dimensões?

In [128]:
a = np.random.randint(1, 10, (3,4))
a

array([[4, 2, 2, 3],
       [6, 8, 1, 3],
       [1, 5, 5, 7]])

In [133]:
a[a>5] #Não sabemos a dimensão final / uma dimensão

array([6, 8, 7])

In [134]:
a[a<5] = 0
a

array([[0, 0, 0, 0],
       [6, 8, 0, 0],
       [0, 5, 5, 7]])

In [137]:
print(a)
mask = [True, False, True, False] # a máscara precisa ter a mesma dimensão da lista
a[mask]

[[0 0 0 0]
 [6 8 0 0]
 [0 5 5 7]]


IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 4

### Indexação com inteiros

In [139]:
a = np.array([0,10,20,30,40,50,60,70,80,90])

In [140]:
a[[1,3,5]]

array([10, 30, 50])

In [141]:
a[[5, 3, 1]]

array([50, 30, 10])

In [142]:
a[[1, 5, 3, 5, 3]]

array([10, 50, 30, 50, 30])

In [143]:
a[[1,3,5]] = 99
a

array([ 0, 99, 20, 99, 40, 99, 60, 70, 80, 90])

In [148]:
a = np.array([[1,2],[3,4],[5,6],[7,8]])
a

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [149]:
a[[1,0], [0,1]]

array([3, 2])

### Operações elemento por elemento

In [150]:
a = np.array([1,2,3,4,5])

In [151]:
a+1

array([2, 3, 4, 5, 6])